---
title: "STAT545-HW04"
author: "Shirlett"
date: "October 6, 2017"
output: github_document

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(message = FALSE)
library(devtools)
library(DT) #provides a nice interface for dataframes
library(gapminder)
library(tidyverse)
library(dplyr) # for grouping and filtering
library(tidyr) #reorganize the values in a data set
library(knitr) #for formatting the output of tables
library(kableExtra) #to create enhanced format for tables
library(xtable)

```

## Reshaping
### Activity #4 - One row per year for each life expectancy min and max rank
```{r results='asis', message=FALSE, warning=FALSE}

# This is taken from the HW windows function example giving the country with both the
# lowest and highest life expectancy (in Asia)
gaptble <- gapminder %>%
  filter(continent == "Asia") %>%
  select(year, country, lifeExp) %>%
  group_by(year) %>%
  filter(min_rank(desc(lifeExp)) < 2 | min_rank(lifeExp) < 2) %>% 
  arrange(year)


kable(gaptble, "html", caption="Countries in Asia with Minimum and Maximum Life Expectancy by Year - Long Format", format.args = list(decimal.mark = '.'), digits=2)


```
```{r}
#Get only the countries with the minimum life expectancies and add new columns
firsttble <- gaptble %>%
  do(head(., n = 1)) %>%
  mutate(LifeType='Minimum_Life', LifeCountry='Minimum_Life_Country') 
  
#Get only the countries with the maximum life expectancies and add new columns
secondtble <- gaptble %>%
  do(tail(., n = 1)) %>%
  mutate(LifeType='Maximum_Life', LifeCountry='Maximum_Life_Country')

#Combine the rows again from the first and second table by binding/appending
recombo_tble <- bind_rows(firsttble, secondtble) %>%
            select(year, LifeCountry, country, LifeType, lifeExp)

#Spread the country value using LifeCountry as key
firstspread <- recombo_tble %>%
  spread(LifeCountry, country) 
  
 
#Do second Spread with the LifeExp value using LifeType as key 
final_spread <- firstspread %>%
  spread(LifeType,lifeExp,  fill=0, drop=TRUE) %>%
  group_by(year) %>%
  summarize(MinLifeCountry=last(Minimum_Life_Country), MinLifeExpectancy=last(Minimum_Life), MaxLifeCountry=first(Maximum_Life_Country),  MaxLifeExpectancy=first(Maximum_Life))  
```


```{r}
kable(final_spread, format='html', digits=2, caption="Countries in Asia with Minimum and Maximum Life Expectancy \nby Year - Wide Format")
```




## JOINING
### Activity #1 - Explore different types of join between gapminder and new dataframe
```{r results='asis', message=FALSE, warning=FALSE}
#Create a new dataframe called gapcont

continent <- c('Africa','Americas','Antarctica','Asia', 'Europe', 'Oceania')
areasqkm <- c(30244049, 42068068, 14000000, 44391162, 10354636, 7686884)
hemisphere <- c('Eastern','Western', 'Western','Eastern', 'Eastern', 'Eastern')

gapcont <- data.frame(continent, areasqkm, hemisphere)

knitr::kable(gapcont, format.args = list(decimal.mark = '.', big.mark = ","),  digits=2, caption="GapCont Table showing Area and Hemisphere for all Continents")

# Left Join
# This results in every single available row in gapminder being returned since all 
# continents in gapminder have a match in gapcont. It also includes the variables
# that match from the second dataframe.
l_join <- left_join(gapminder, gapcont, by='continent')
l_join %>%
  filter(year==2007 | is.na(year)) %>%
  select(continent, pop, areasqkm, hemisphere) %>%
  arrange(continent) %>%
  group_by(continent, areasqkm, hemisphere) %>%
  summarise(totalpop=sum(as.numeric(pop))) %>%
  knitr::kable(format.args = list(decimal.mark = '.', big.mark = ","),  digits=2, caption="Left Join Result Summary")

# Right Join
# This results in every single available row in gapminder in addition to the one row 
# in gapcont that does not have a match which is Antarctica.
r_join <- right_join(gapminder, gapcont, by='continent') 

r_join %>%
  filter(year==2007 | is.na(year)) %>%
  select(continent, pop, areasqkm, hemisphere) %>%
  arrange(continent) %>%
  group_by(continent, areasqkm, hemisphere) %>%
  summarise(totalpop=sum(as.numeric(pop))) %>%
  knitr::kable(format.args = list(decimal.mark = '.', big.mark = ","),   digits=2, caption="Right Join Result Summary")

# Inner Join
# This results in every single available row in gapminder being returned since all 
# continents in gapminder has a match in gapcont. All combinations of the matches are 
# returned. All variables from both tables are combined in the order of the inner join # function.
i_join <- inner_join(gapminder, gapcont, by='continent')
i_join %>%
  filter(year==2007 | is.na(year)) %>%
  select(continent, pop, areasqkm, hemisphere) %>%
  arrange(continent) %>%
  group_by(continent, areasqkm, hemisphere) %>%
  summarise(totalpop=sum(as.numeric(pop))) %>%
  knitr::kable(format.args = list(decimal.mark = '.', big.mark = ","),  digits=2, caption="Inner Join Result Summary")

# Full Join
# This results in all rows in both the gapminder and the gapcont being returned even if # some columns are null
f_join <- full_join(gapminder, gapcont, by='continent')
f_join %>%
  filter(year==2007 | is.na(year)) %>%
  select(continent, pop, areasqkm, hemisphere) %>%
  arrange(continent) %>%
  group_by(continent, areasqkm, hemisphere) %>%
  summarise(totalpop=sum(as.numeric(pop))) %>%
  knitr::kable(format.args = list(decimal.mark = '.', big.mark = ","),   digits=2, caption= "Full Join Result Summary")

# Semi-Join
# This results in only the rows in which continent matches in both the gapminder and 
# gapcont but no variables from gapcont are returned
s_join <- semi_join(gapminder, gapcont, by='continent')
s_join %>%
  filter(year==2007 | is.na(year)) %>%
  select(continent, pop) %>%
  arrange(continent) %>%
  group_by(continent) %>%
  summarise(totalpop=sum(as.numeric(pop))) %>%
  knitr::kable(format.args = list(decimal.mark = '.', big.mark = ","),  digits=2, caption= "Semi Join Result Summary")

# Anti-Join with gapminder as the first dataset
# This results in no rows being returned since all of the continents in gapminder have # a match in gapcont
a_join <- anti_join(gapminder, gapcont, by='continent')
knitr::kable(a_join, format.args = list(decimal.mark = '.', big.mark = ","),  digits=2, caption="Anti Join Result Summary - Gapminder as First Dataframe")

# Anti-join with gapminder as the second dataset
# This results in only one row being returned since one of the continents in gapcont  
# do not have a match in gapminder
a_join_sec <- anti_join(gapcont, gapminder,  by='continent')

knitr::kable(a_join_sec, format.args = list(decimal.mark = '.', big.mark = ","),   digits=2, caption="Anti Join Result Summary - Gapminder as Second Dataframe")


```

### Activity 3 - Merging and Matching

```{r message=FALSE, warning=FALSE}
# Merging

# This merges two data frames horizontally based on at least one similar variable. The # result of doing a full merge of the gapminder dataset and the second gapcont 
# dataframe is the same as full join in dyplr where all values and all rows are 
# retained. There #are also parameters that can be added to the merge function to  
# mimic a left join, #right join or inner join using "all*".

#Same results as a full join
all_mrge <- merge(gapminder, gapcont, "continent", all=TRUE)
str(all_mrge)

#Same results as a inner join
inner_mrge <- merge(gapminder, gapcont, "continent", all=FALSE)
str(inner_mrge)

#Same results as a left join
left_mrge <- merge(gapminder, gapcont, "continent", all.x=TRUE)
str(left_mrge)

#Same results as a right join
right_mrge <- merge(gapminder, gapcont, "continent", all.y=TRUE)
str(right_mrge)


```

```{r message=FALSE, warning=FALSE}
#Match

# This function returns a vector of the position of the first occurrence of a 
# continent from gapcont in gapminder. The example below shows that Africa is first 
# found on row 25 in the gapminder dataset. This function does not join together a 
# dataset, but it is useful for selecting the appropriate join/merge function, 
# especially left or right join. The match function will also inform the user of any 
# missing variables that should have been present in the two datasets when results 
# show NA.

match(gapcont$continent, gapminder$continent)




```

