all:UNdata_Export_ALL_Factors.xls
	
clean: rm -f UNdata_Export_ALL_Factors.xls

UNdata_Export_ALL_Factors.xls:
	curl -o  internet.usage.xls https://github.com/Shirlett/STAT545-hw-Hall-Shirlett/blob/master/HW07/UNdata_Export_ALL_Factors.xls
	
	