all:internet.usage.xls
	
clean: rm -f internet.usage.xls

internet.usage.xls:
	curl -o  internet.usage.xls https://github.com/Shirlett/STAT545-hw-Hall-Shirlett/blob/master/HW07/UNdata_Export_ALL_Factors.xls
	
	