---
title: "STAT545-HW07-Step1"
author: "Shirlett"
date: "November 12, 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
setwd("~/myrepositories/STAT545-hw-Hall-Shirlett/HW07")
library(tidyverse)
library(knitr) #for formatting the output of tables
library(dplyr) # for grouping and filtering
library(forcats) #used to manipulate factors for ordering, lumping etc
library(gridExtra) #used to layout tables and charts in a grid
library(grid) #used to layout tables and charts in a grid
library(readxl) #used to read excel file formats
library(RColorBrewer) #has a set of colors for print and graphics
library(scales) # to modify the appearance of axis values
library(ggthemes) #additional color themes
library(devtools)
library(plotrix) # creates exploded pie charts
library(ggplot2)
```

#Import Datasets
```{r}
#Import Datasets from separate tabs 
 #Data for Internet Usage per 100 inhabitants in 203 countries across the world from 2008 to 2015
 Internet_Users <- read_excel("./UNdata_Export_ALL_Factors.xls", sheet = "Internet")
 
#Data for Mobile Usage per 100 inhabitants where available for each country and year
 Mobile_Users <- read_excel("./UNdata_Export_ALL_Factors.xls", sheet = "Mobile")

#Data for Population counts in urban and rural areas where available for each country and year 
 Location <- read_excel("./UNdata_Export_ALL_Factors.xls", sheet = "Location")
 
#Data for Gross National Income where available for each country and year
 GNI <- read_excel("./UNdata_Export_ALL_Factors.xls", sheet = "GNI")
 
#Data for Life Expectancy where available for each country and year
 Life_Exp <- read_excel("./UNdata_Export_ALL_Factors.xls", sheet = "Life")

#Data for Percentage of population with at least a primary school education where available for #each country and year 
 Schooling <- read_excel("./UNdata_Export_ALL_Factors.xls", sheet = "Schooling")

#Data for the dominant language spoken in  each country 
 Language <- read_excel("./UNdata_Export_ALL_Factors.xls", sheet = "Language")
 
#Data for the percentage of each population with access to electricity where available for each
#country and year
 Electricity <- read_excel("./UNdata_Export_ALL_Factors.xls", sheet = "Electricity")
 
#Data for the Adult Unemployment rate where available for each country and year
 Unemployment <- read_excel("./UNdata_Export_ALL_Factors.xls", sheet = "Unemployment")

```

#Data Cleaning
```{r}

#Remove the duplicating rows where earlier census results for Rural/Urban areas are included for the same year. 

#This code takes the higher value for each duplicated row since the most recent census collection
#is likely to be the most correct.

clean_location <- Location %>%
        group_by(Country, Year, Area) %>%
        mutate(Valid_Pop = max(Population)) %>%
        select(Country, Year, Area, Valid_Pop) %>%
        unique()
  
#This gets percentage values of rural vs urban occupation for each country
per_rural <- clean_location %>%
                group_by(Country, Year) %>%
                mutate(Tot_pop  = sum(Valid_Pop)) %>%
                filter(Area=="Rural") %>%
                mutate(Rural_Pop=Valid_Pop, Percent_rural  = ((Valid_Pop/Tot_pop)*100), Percent_urban  = (((Tot_pop-Valid_Pop)/Tot_pop)*100)) %>%
                select(Country, Year, Tot_pop, Percent_rural, Percent_urban)

#Merge all tables by Country and Year except Language which is the same for all years
Data1 <- merge(Internet_Users, Mobile_Users, by=c("Country", "Year"), all.x=TRUE)
Data2 <- merge(Data1, per_rural, by=c("Country", "Year"), all.x=TRUE)
Data3 <- merge(Data2, GNI, by=c("Country", "Year"), all.x=TRUE)
Data4 <- merge(Data3, Life_Exp, by=c("Country", "Year"), all.x=TRUE)
Data5 <- merge(Data4, Schooling, by=c("Country", "Year"), all.x=TRUE)
Data6 <- merge(Data5, Electricity, by=c("Country", "Year"), all.x=TRUE)
Data7 <- merge(Data6, Unemployment, by=c("Country", "Year"), all.x=TRUE)

#Drop a column related to Age Group and sort by Country Name
All_Data  <- merge(Data7, Language, by=c("Country"), all.x=TRUE) %>%
             within(rm("Age group")) %>%
						 arrange(Country)
All_Data 
```


```{r fig.height=20}
#Obtain a first look at the ranking of Internet usage by factoring Country by Internet Usage in a dot plot

theme_set(theme_classic())

internet_usage <- All_Data %>%
									group_by(Country) %>%
                  subset(Year == max(Year)) %>%
                  select(Country, Internet_Users_per_100) %>%
   								ggplot(aes(x=reorder(Country, Internet_Users_per_100), Internet_Users_per_100)) + 
  geom_point(col="tomato2", size=3) +   # Draw points
  geom_segment(aes(x=Country, 
                   xend=Country, 
                   y=min(0), 
                   yend=max(Internet_Users_per_100)), 
                 linetype="dashed", 
               size=0.1) +   # Draw dashed lines
  labs(title="Dot Plot", 
       subtitle="Internet Usage by Country in 2015", 
       caption="source: UN",
  		 y = "Internet Usage per 100 inhabitants", x= "Country") +  
  coord_flip() 

internet_usage

 		
```

